create database Academy
go
use  Academy

go
create table Groups(
ID int primary key not null identity(1,1),
Name nvarchar(10) not null unique check(Name<>' '),
Rating int not null check(Rating<6 and Rating>-1),
Year int not null check(Year>0 and Year<6)
)
go
create table Departments(
ID int primary key not null identity(1,1),
Financing money not null default 0 check(Financing>-1),
Name nvarchar(100) not null unique check(Name<>' ')
)
go
create table Faculties(
ID int primary key not null identity(1,1),
Name nvarchar(100) not null unique check(Name<>' ')
)
go
create table Teachers(
ID int primary key not null identity(1,1),
EmploymentDate date not null check(EmploymentDate>'31-12-1989')
)
go

insert into Groups (ID, Name, Rating, Year) values (1, 'Cindra', 4, 8);
insert into Groups (ID, Name, Rating, Year) values (2, 'Luce', 6, 8);
insert into Groups (ID, Name, Rating, Year) values (3, 'Marketa', 3, 3);
insert into Groups (ID, Name, Rating, Year) values (4, 'Beltran', 2, 1);
insert into Groups (ID, Name, Rating, Year) values (5, 'Raddy', 8, 1);
insert into Groups (ID, Name, Rating, Year) values (6, 'Kaleena', 3, 5);
insert into Groups (ID, Name, Rating, Year) values (7, 'Brenn', 9, 5);
insert into Groups (ID, Name, Rating, Year) values (8, 'Jeri', 2, 1);
insert into Groups (ID, Name, Rating, Year) values (9, 'Nike', 10, 4);
insert into Groups (ID, Name, Rating, Year) values (10, 'Sigismond', 2, 4);
insert into Groups (ID, Name, Rating, Year) values (11, 'Federica', 2, 6);
insert into Groups (ID, Name, Rating, Year) values (12, 'Padraic', 3, 4);
insert into Groups (ID, Name, Rating, Year) values (13, 'Celestyna', 6, 2);
insert into Groups (ID, Name, Rating, Year) values (14, 'Tandi', 8, 6);
insert into Groups (ID, Name, Rating, Year) values (15, 'Andree', 7, 10);
insert into Groups (ID, Name, Rating, Year) values (16, 'Boigie', 1, 10);
insert into Groups (ID, Name, Rating, Year) values (17, 'Geoffry', 6, 7);
insert into Groups (ID, Name, Rating, Year) values (18, 'Chrissie', 2, 6);
insert into Groups (ID, Name, Rating, Year) values (19, 'Mehetabel', 2, 10);
insert into Groups (ID, Name, Rating, Year) values (20, 'Blair', 1, 1);
insert into Groups (ID, Name, Rating, Year) values (21, 'Ricard', 10, 10);
insert into Groups (ID, Name, Rating, Year) values (22, 'Clevie', 4, 8);
insert into Groups (ID, Name, Rating, Year) values (23, 'Mada', 4, 8);
insert into Groups (ID, Name, Rating, Year) values (24, 'Frederique', 1, 2);
insert into Groups (ID, Name, Rating, Year) values (25, 'Beverie', 7, 2);
insert into Groups (ID, Name, Rating, Year) values (26, 'Liesa', 8, 4);
insert into Groups (ID, Name, Rating, Year) values (27, 'Florida', 4, 1);
insert into Groups (ID, Name, Rating, Year) values (28, 'Isahella', 5, 5);
insert into Groups (ID, Name, Rating, Year) values (29, 'Salli', 1, 5);
insert into Groups (ID, Name, Rating, Year) values (30, 'Masha', 2, 1);
insert into Groups (ID, Name, Rating, Year) values (31, 'Bernita', 2, 7);
insert into Groups (ID, Name, Rating, Year) values (32, 'Rex', 10, 2);
insert into Groups (ID, Name, Rating, Year) values (33, 'Hugues', 4, 6);
insert into Groups (ID, Name, Rating, Year) values (34, 'Alexia', 5, 9);
insert into Groups (ID, Name, Rating, Year) values (35, 'Hobey', 2, 3);
insert into Groups (ID, Name, Rating, Year) values (36, 'Archibald', 6, 9);
insert into Groups (ID, Name, Rating, Year) values (37, 'Miguelita', 4, 1);
insert into Groups (ID, Name, Rating, Year) values (38, 'Karisa', 1, 2);
insert into Groups (ID, Name, Rating, Year) values (39, 'Roger', 3, 10);
insert into Groups (ID, Name, Rating, Year) values (40, 'Karoly', 5, 4);
insert into Groups (ID, Name, Rating, Year) values (41, 'Gordy', 7, 10);
insert into Groups (ID, Name, Rating, Year) values (42, 'Emmett', 9, 3);
insert into Groups (ID, Name, Rating, Year) values (43, 'Giuditta', 9, 6);
insert into Groups (ID, Name, Rating, Year) values (44, 'Chaddy', 8, 7);
insert into Groups (ID, Name, Rating, Year) values (45, 'Hermione', 3, 5);
insert into Groups (ID, Name, Rating, Year) values (46, 'Ronda', 3, 3);
insert into Groups (ID, Name, Rating, Year) values (47, 'Susana', 2, 7);
insert into Groups (ID, Name, Rating, Year) values (48, 'Lynnette', 5, 10);
insert into Groups (ID, Name, Rating, Year) values (49, 'Madeline', 9, 7);
insert into Groups (ID, Name, Rating, Year) values (50, 'Carmon', 3, 5);
insert into Groups (ID, Name, Rating, Year) values (51, 'Freeman', 6, 5);
insert into Groups (ID, Name, Rating, Year) values (52, 'Saw', 10, 2);
insert into Groups (ID, Name, Rating, Year) values (53, 'Leora', 4, 9);
insert into Groups (ID, Name, Rating, Year) values (54, 'Aube', 6, 4);
insert into Groups (ID, Name, Rating, Year) values (55, 'Tilda', 5, 5);
insert into Groups (ID, Name, Rating, Year) values (56, 'Domini', 8, 3);
insert into Groups (ID, Name, Rating, Year) values (57, 'Judah', 6, 10);
insert into Groups (ID, Name, Rating, Year) values (58, 'Naomi', 4, 8);
insert into Groups (ID, Name, Rating, Year) values (59, 'Desdemona', 6, 9);
insert into Groups (ID, Name, Rating, Year) values (60, 'Reuven', 10, 8);
insert into Groups (ID, Name, Rating, Year) values (61, 'Harman', 10, 9);
insert into Groups (ID, Name, Rating, Year) values (62, 'Noam', 7, 5);
insert into Groups (ID, Name, Rating, Year) values (63, 'Laurel', 1, 1);
insert into Groups (ID, Name, Rating, Year) values (64, 'Donny', 5, 8);
insert into Groups (ID, Name, Rating, Year) values (65, 'Cathlene', 6, 1);
insert into Groups (ID, Name, Rating, Year) values (66, 'Teodora', 9, 4);
insert into Groups (ID, Name, Rating, Year) values (67, 'Mada', 1, 4);
insert into Groups (ID, Name, Rating, Year) values (68, 'Hube', 10, 1);
insert into Groups (ID, Name, Rating, Year) values (69, 'Latashia', 7, 8);
insert into Groups (ID, Name, Rating, Year) values (70, 'Marchall', 4, 1);
insert into Groups (ID, Name, Rating, Year) values (71, 'Helen-elizabeth', 2, 6);
insert into Groups (ID, Name, Rating, Year) values (72, 'Danica', 1, 9);
insert into Groups (ID, Name, Rating, Year) values (73, 'Dietrich', 1, 3);
insert into Groups (ID, Name, Rating, Year) values (74, 'Shanda', 9, 1);
insert into Groups (ID, Name, Rating, Year) values (75, 'Xavier', 2, 4);
insert into Groups (ID, Name, Rating, Year) values (76, 'Lem', 4, 9);
insert into Groups (ID, Name, Rating, Year) values (77, 'Viole', 8, 8);
insert into Groups (ID, Name, Rating, Year) values (78, 'Candi', 6, 10);
insert into Groups (ID, Name, Rating, Year) values (79, 'Nalani', 8, 1);
insert into Groups (ID, Name, Rating, Year) values (80, 'Royce', 5, 2);
insert into Groups (ID, Name, Rating, Year) values (81, 'Roma', 2, 9);
insert into Groups (ID, Name, Rating, Year) values (82, 'Jaimie', 8, 8);
insert into Groups (ID, Name, Rating, Year) values (83, 'Annemarie', 9, 10);
insert into Groups (ID, Name, Rating, Year) values (84, 'Eugine', 5, 7);
insert into Groups (ID, Name, Rating, Year) values (85, 'Bevin', 3, 6);
insert into Groups (ID, Name, Rating, Year) values (86, 'Olva', 1, 10);
insert into Groups (ID, Name, Rating, Year) values (87, 'Finn', 7, 3);
insert into Groups (ID, Name, Rating, Year) values (88, 'Chaddie', 3, 10);
insert into Groups (ID, Name, Rating, Year) values (89, 'Carolyn', 4, 2);
insert into Groups (ID, Name, Rating, Year) values (90, 'Anissa', 2, 2);
insert into Groups (ID, Name, Rating, Year) values (91, 'Dyan', 5, 7);
insert into Groups (ID, Name, Rating, Year) values (92, 'Emory', 7, 5);
insert into Groups (ID, Name, Rating, Year) values (93, 'Anson', 4, 3);
insert into Groups (ID, Name, Rating, Year) values (94, 'Jessie', 9, 7);
insert into Groups (ID, Name, Rating, Year) values (95, 'Appolonia', 8, 4);
insert into Groups (ID, Name, Rating, Year) values (96, 'Antin', 9, 9);
insert into Groups (ID, Name, Rating, Year) values (97, 'Tisha', 1, 8);
insert into Groups (ID, Name, Rating, Year) values (98, 'Erhart', 4, 1);
insert into Groups (ID, Name, Rating, Year) values (99, 'Bette', 6, 10);
insert into Groups (ID, Name, Rating, Year) values (100, 'Kennith', 7, 4);
insert into Departments (ID, Financing, Name) values (1, '$1567.84', 'Sonnnie');
insert into Departments (ID, Financing, Name) values (2, '$9925.22', 'Sutherland');
insert into Departments (ID, Financing, Name) values (3, '$4686.05', 'Hilliary');
insert into Departments (ID, Financing, Name) values (4, '$3737.51', 'Bobinette');
insert into Departments (ID, Financing, Name) values (5, '$2866.13', 'Colet');
insert into Departments (ID, Financing, Name) values (6, '$2660.10', 'Shelby');
insert into Departments (ID, Financing, Name) values (7, '$6838.69', 'Corbett');
insert into Departments (ID, Financing, Name) values (8, '$502.66', 'Binnie');
insert into Departments (ID, Financing, Name) values (9, '$7994.77', 'Maggi');
insert into Departments (ID, Financing, Name) values (10, '$7841.07', 'Anica');
insert into Departments (ID, Financing, Name) values (11, '$6640.95', 'Elianora');
insert into Departments (ID, Financing, Name) values (12, '$8752.14', 'Roshelle');
insert into Departments (ID, Financing, Name) values (13, '$124.24', 'Netta');
insert into Departments (ID, Financing, Name) values (14, '$2934.56', 'Enriqueta');
insert into Departments (ID, Financing, Name) values (15, '$6563.86', 'Fredek');
insert into Departments (ID, Financing, Name) values (16, '$4330.35', 'Floyd');
insert into Departments (ID, Financing, Name) values (17, '$3916.08', 'Doralin');
insert into Departments (ID, Financing, Name) values (18, '$6647.35', 'Annmaria');
insert into Departments (ID, Financing, Name) values (19, '$5285.46', 'Tadd');
insert into Departments (ID, Financing, Name) values (20, '$6109.51', 'Alyosha');
insert into Departments (ID, Financing, Name) values (21, '$994.98', 'Corella');
insert into Departments (ID, Financing, Name) values (22, '$3894.70', 'Archie');
insert into Departments (ID, Financing, Name) values (23, '$2328.19', 'Mikaela');
insert into Departments (ID, Financing, Name) values (24, '$9196.32', 'Niki');
insert into Departments (ID, Financing, Name) values (25, '$2309.66', 'Shepard');
insert into Departments (ID, Financing, Name) values (26, '$3651.21', 'Nikaniki');
insert into Departments (ID, Financing, Name) values (27, '$4499.22', 'Jacqueline');
insert into Departments (ID, Financing, Name) values (28, '$8985.16', 'Emmi');
insert into Departments (ID, Financing, Name) values (29, '$4853.78', 'Dulce');
insert into Departments (ID, Financing, Name) values (30, '$6537.62', 'Arabel');
insert into Departments (ID, Financing, Name) values (31, '$4712.12', 'Roberto');
insert into Departments (ID, Financing, Name) values (32, '$193.79', 'Risa');
insert into Departments (ID, Financing, Name) values (33, '$2285.62', 'Sisely');
insert into Departments (ID, Financing, Name) values (34, '$7039.75', 'Bess');
insert into Departments (ID, Financing, Name) values (35, '$446.58', 'Emyle');
insert into Departments (ID, Financing, Name) values (36, '$3012.65', 'Celie');
insert into Departments (ID, Financing, Name) values (37, '$6793.81', 'Bel');
insert into Departments (ID, Financing, Name) values (38, '$7570.90', 'Jae');
insert into Departments (ID, Financing, Name) values (39, '$678.40', 'Philip');
insert into Departments (ID, Financing, Name) values (40, '$2095.40', 'Harman');
insert into Departments (ID, Financing, Name) values (41, '$470.22', 'Olin');
insert into Departments (ID, Financing, Name) values (42, '$8441.29', 'Jaime');
insert into Departments (ID, Financing, Name) values (43, '$1771.43', 'Rici');
insert into Departments (ID, Financing, Name) values (44, '$8395.88', 'Timothea');
insert into Departments (ID, Financing, Name) values (45, '$5171.47', 'Nicki');
insert into Departments (ID, Financing, Name) values (46, '$5585.78', 'Reuben');
insert into Departments (ID, Financing, Name) values (47, '$1591.44', 'Yard');
insert into Departments (ID, Financing, Name) values (48, '$7536.03', 'Ruthanne');
insert into Departments (ID, Financing, Name) values (49, '$156.33', 'Kelsey');
insert into Departments (ID, Financing, Name) values (50, '$9248.62', 'Minette');
insert into Departments (ID, Financing, Name) values (51, '$4498.60', 'Donnajean');
insert into Departments (ID, Financing, Name) values (52, '$8614.87', 'Jacquenetta');
insert into Departments (ID, Financing, Name) values (53, '$1012.49', 'Demetri');
insert into Departments (ID, Financing, Name) values (54, '$7221.84', 'Idell');
insert into Departments (ID, Financing, Name) values (55, '$6482.71', 'Viva');
insert into Departments (ID, Financing, Name) values (56, '$3534.04', 'Meyer');
insert into Departments (ID, Financing, Name) values (57, '$3335.20', 'Archibold');
insert into Departments (ID, Financing, Name) values (58, '$5458.32', 'Geneva');
insert into Departments (ID, Financing, Name) values (59, '$4007.20', 'Killy');
insert into Departments (ID, Financing, Name) values (60, '$1658.63', 'Rudolf');
insert into Departments (ID, Financing, Name) values (61, '$6617.63', 'Merci');
insert into Departments (ID, Financing, Name) values (62, '$7348.16', 'Kelcey');
insert into Departments (ID, Financing, Name) values (63, '$8481.98', 'Letisha');
insert into Departments (ID, Financing, Name) values (64, '$9652.10', 'Gerry');
insert into Departments (ID, Financing, Name) values (65, '$1484.89', 'Gwyneth');
insert into Departments (ID, Financing, Name) values (66, '$7080.39', 'Adiana');
insert into Departments (ID, Financing, Name) values (67, '$2527.67', 'Desmund');
insert into Departments (ID, Financing, Name) values (68, '$5546.31', 'Abe');
insert into Departments (ID, Financing, Name) values (69, '$6549.19', 'Caren');
insert into Departments (ID, Financing, Name) values (70, '$8855.55', 'Rene');
insert into Departments (ID, Financing, Name) values (71, '$5242.24', 'Magdaia');
insert into Departments (ID, Financing, Name) values (72, '$9741.69', 'Vladimir');
insert into Departments (ID, Financing, Name) values (73, '$4475.25', 'Persis');
insert into Departments (ID, Financing, Name) values (74, '$9788.24', 'Faina');
insert into Departments (ID, Financing, Name) values (75, '$6332.07', 'Trude');
insert into Departments (ID, Financing, Name) values (76, '$4440.08', 'Hayyim');
insert into Departments (ID, Financing, Name) values (77, '$9034.06', 'Bunni');
insert into Departments (ID, Financing, Name) values (78, '$3472.90', 'Isidore');
insert into Departments (ID, Financing, Name) values (79, '$6172.85', 'Dosi');
insert into Departments (ID, Financing, Name) values (80, '$7114.86', 'Stirling');
insert into Departments (ID, Financing, Name) values (81, '$9066.57', 'Melanie');
insert into Departments (ID, Financing, Name) values (82, '$847.04', 'Silas');
insert into Departments (ID, Financing, Name) values (83, '$9094.11', 'Jacquelynn');
insert into Departments (ID, Financing, Name) values (84, '$7320.63', 'Antonie');
insert into Departments (ID, Financing, Name) values (85, '$3491.34', 'Harwell');
insert into Departments (ID, Financing, Name) values (86, '$4783.50', 'Fabian');
insert into Departments (ID, Financing, Name) values (87, '$8318.16', 'Renaud');
insert into Departments (ID, Financing, Name) values (88, '$8280.49', 'Horatius');
insert into Departments (ID, Financing, Name) values (89, '$4756.50', 'Jon');
insert into Departments (ID, Financing, Name) values (90, '$425.59', 'Persis');
insert into Departments (ID, Financing, Name) values (91, '$65.63', 'Richardo');
insert into Departments (ID, Financing, Name) values (92, '$6385.26', 'Becka');
insert into Departments (ID, Financing, Name) values (93, '$4957.10', 'Malinda');
insert into Departments (ID, Financing, Name) values (94, '$8193.56', 'Merilyn');
insert into Departments (ID, Financing, Name) values (95, '$9119.33', 'Lulita');
insert into Departments (ID, Financing, Name) values (96, '$7762.26', 'Cilka');
insert into Departments (ID, Financing, Name) values (97, '$8462.24', 'Tildy');
insert into Departments (ID, Financing, Name) values (98, '$7372.78', 'Fairfax');
insert into Departments (ID, Financing, Name) values (99, '$7617.14', 'Elva');
insert into Departments (ID, Financing, Name) values (100, '$4018.45', 'Carlynne');
insert into Faculties (ID, Name) values (1, 'Grete');
insert into Faculties (ID, Name) values (2, 'Burt');
insert into Faculties (ID, Name) values (3, 'Florenza');
insert into Faculties (ID, Name) values (4, 'Kalie');
insert into Faculties (ID, Name) values (5, 'Leodora');
insert into Faculties (ID, Name) values (6, 'Lenora');
insert into Faculties (ID, Name) values (7, 'Isador');
insert into Faculties (ID, Name) values (8, 'Killie');
insert into Faculties (ID, Name) values (9, 'Kelley');
insert into Faculties (ID, Name) values (10, 'Nicolas');
insert into Faculties (ID, Name) values (11, 'Alan');
insert into Faculties (ID, Name) values (12, 'Omero');
insert into Faculties (ID, Name) values (13, 'Edin');
insert into Faculties (ID, Name) values (14, 'Rachele');
insert into Faculties (ID, Name) values (15, 'Patti');
insert into Faculties (ID, Name) values (16, 'Olympie');
insert into Faculties (ID, Name) values (17, 'Layne');
insert into Faculties (ID, Name) values (18, 'Waylen');
insert into Faculties (ID, Name) values (19, 'Janeva');
insert into Faculties (ID, Name) values (20, 'Curtice');
insert into Faculties (ID, Name) values (21, 'Allyson');
insert into Faculties (ID, Name) values (22, 'Celestyna');
insert into Faculties (ID, Name) values (23, 'Maximilianus');
insert into Faculties (ID, Name) values (24, 'Eugenie');
insert into Faculties (ID, Name) values (25, 'Cristi');
insert into Faculties (ID, Name) values (26, 'Elfie');
insert into Faculties (ID, Name) values (27, 'Ellen');
insert into Faculties (ID, Name) values (28, 'Kelby');
insert into Faculties (ID, Name) values (29, 'Channa');
insert into Faculties (ID, Name) values (30, 'Aldwin');
insert into Faculties (ID, Name) values (31, 'Sabine');
insert into Faculties (ID, Name) values (32, 'Abraham');
insert into Faculties (ID, Name) values (33, 'Danyette');
insert into Faculties (ID, Name) values (34, 'Gertie');
insert into Faculties (ID, Name) values (35, 'Giulietta');
insert into Faculties (ID, Name) values (36, 'Thain');
insert into Faculties (ID, Name) values (37, 'Latia');
insert into Faculties (ID, Name) values (38, 'Amby');
insert into Faculties (ID, Name) values (39, 'Vaughan');
insert into Faculties (ID, Name) values (40, 'Selene');
insert into Faculties (ID, Name) values (41, 'Kermy');
insert into Faculties (ID, Name) values (42, 'Dacy');
insert into Faculties (ID, Name) values (43, 'Wyatan');
insert into Faculties (ID, Name) values (44, 'Joella');
insert into Faculties (ID, Name) values (45, 'Marijn');
insert into Faculties (ID, Name) values (46, 'Vincenty');
insert into Faculties (ID, Name) values (47, 'Ibrahim');
insert into Faculties (ID, Name) values (48, 'Tate');
insert into Faculties (ID, Name) values (49, 'Dicky');
insert into Faculties (ID, Name) values (50, 'Rozalin');
insert into Faculties (ID, Name) values (51, 'Moreen');
insert into Faculties (ID, Name) values (52, 'Horten');
insert into Faculties (ID, Name) values (53, 'Emmi');
insert into Faculties (ID, Name) values (54, 'Tadd');
insert into Faculties (ID, Name) values (55, 'Humbert');
insert into Faculties (ID, Name) values (56, 'Kimble');
insert into Faculties (ID, Name) values (57, 'Percival');
insert into Faculties (ID, Name) values (58, 'Roch');
insert into Faculties (ID, Name) values (59, 'Alain');
insert into Faculties (ID, Name) values (60, 'Harlie');
insert into Faculties (ID, Name) values (61, 'Fiorenze');
insert into Faculties (ID, Name) values (62, 'Millard');
insert into Faculties (ID, Name) values (63, 'Kin');
insert into Faculties (ID, Name) values (64, 'Fidela');
insert into Faculties (ID, Name) values (65, 'Gunilla');
insert into Faculties (ID, Name) values (66, 'Janie');
insert into Faculties (ID, Name) values (67, 'Miguel');
insert into Faculties (ID, Name) values (68, 'Glenna');
insert into Faculties (ID, Name) values (69, 'Nanice');
insert into Faculties (ID, Name) values (70, 'Honoria');
insert into Faculties (ID, Name) values (71, 'Matty');
insert into Faculties (ID, Name) values (72, 'Jonell');
insert into Faculties (ID, Name) values (73, 'Alfy');
insert into Faculties (ID, Name) values (74, 'Patricia');
insert into Faculties (ID, Name) values (75, 'Myron');
insert into Faculties (ID, Name) values (76, 'Ellerey');
insert into Faculties (ID, Name) values (77, 'Meta');
insert into Faculties (ID, Name) values (78, 'Maire');
insert into Faculties (ID, Name) values (79, 'Aileen');
insert into Faculties (ID, Name) values (80, 'Ronni');
insert into Faculties (ID, Name) values (81, 'Brook');
insert into Faculties (ID, Name) values (82, 'Brewer');
insert into Faculties (ID, Name) values (83, 'Allyce');
insert into Faculties (ID, Name) values (84, 'Starr');
insert into Faculties (ID, Name) values (85, 'Katie');
insert into Faculties (ID, Name) values (86, 'Euphemia');
insert into Faculties (ID, Name) values (87, 'Alvan');
insert into Faculties (ID, Name) values (88, 'Aloysius');
insert into Faculties (ID, Name) values (89, 'Clemmie');
insert into Faculties (ID, Name) values (90, 'Ketty');
insert into Faculties (ID, Name) values (91, 'Jeremiah');
insert into Faculties (ID, Name) values (92, 'Sawyer');
insert into Faculties (ID, Name) values (93, 'Skylar');
insert into Faculties (ID, Name) values (94, 'Briggs');
insert into Faculties (ID, Name) values (95, 'Constanta');
insert into Faculties (ID, Name) values (96, 'Ofella');
insert into Faculties (ID, Name) values (97, 'Lila');
insert into Faculties (ID, Name) values (98, 'Stafani');
insert into Faculties (ID, Name) values (99, 'Lorilee');
insert into Faculties (ID, Name) values (100, 'Annadiane');
insert into Teachers (ID, EmploymentDate) values (1, '27/7/2024');
insert into Teachers (ID, EmploymentDate) values (2, '7/10/2011');
insert into Teachers (ID, EmploymentDate) values (3, '22/1/2000');
insert into Teachers (ID, EmploymentDate) values (4, '8/6/2011');
insert into Teachers (ID, EmploymentDate) values (5, '12/7/2019');
insert into Teachers (ID, EmploymentDate) values (6, '18/7/2024');
insert into Teachers (ID, EmploymentDate) values (7, '13/8/1991');
insert into Teachers (ID, EmploymentDate) values (8, '15/12/2021');
insert into Teachers (ID, EmploymentDate) values (9, '12/6/2000');
insert into Teachers (ID, EmploymentDate) values (10, '15/10/2007');
insert into Teachers (ID, EmploymentDate) values (11, '12/5/2010');
insert into Teachers (ID, EmploymentDate) values (12, '22/11/2018');
insert into Teachers (ID, EmploymentDate) values (13, '4/12/2024');
insert into Teachers (ID, EmploymentDate) values (14, '4/9/1994');
insert into Teachers (ID, EmploymentDate) values (15, '16/9/2012');
insert into Teachers (ID, EmploymentDate) values (16, '10/7/1993');
insert into Teachers (ID, EmploymentDate) values (17, '26/10/2001');
insert into Teachers (ID, EmploymentDate) values (18, '17/1/2018');
insert into Teachers (ID, EmploymentDate) values (19, '17/10/2013');
insert into Teachers (ID, EmploymentDate) values (20, '9/11/1997');
insert into Teachers (ID, EmploymentDate) values (21, '10/3/1995');
insert into Teachers (ID, EmploymentDate) values (22, '17/7/1996');
insert into Teachers (ID, EmploymentDate) values (23, '11/12/2011');
insert into Teachers (ID, EmploymentDate) values (24, '7/10/2008');
insert into Teachers (ID, EmploymentDate) values (25, '17/4/2021');
insert into Teachers (ID, EmploymentDate) values (26, '5/10/2007');
insert into Teachers (ID, EmploymentDate) values (27, '3/4/2019');
insert into Teachers (ID, EmploymentDate) values (28, '7/8/2011');
insert into Teachers (ID, EmploymentDate) values (29, '20/6/1996');
insert into Teachers (ID, EmploymentDate) values (30, '1/9/2012');
insert into Teachers (ID, EmploymentDate) values (31, '12/7/1992');
insert into Teachers (ID, EmploymentDate) values (32, '16/7/2025');
insert into Teachers (ID, EmploymentDate) values (33, '19/3/1993');
insert into Teachers (ID, EmploymentDate) values (34, '8/10/1993');
insert into Teachers (ID, EmploymentDate) values (35, '21/7/2009');
insert into Teachers (ID, EmploymentDate) values (36, '19/8/2024');
insert into Teachers (ID, EmploymentDate) values (37, '15/11/1997');
insert into Teachers (ID, EmploymentDate) values (38, '4/5/2014');
insert into Teachers (ID, EmploymentDate) values (39, '20/5/2003');
insert into Teachers (ID, EmploymentDate) values (40, '14/8/2019');
insert into Teachers (ID, EmploymentDate) values (41, '14/8/1997');
insert into Teachers (ID, EmploymentDate) values (42, '29/12/1991');
insert into Teachers (ID, EmploymentDate) values (43, '21/8/2017');
insert into Teachers (ID, EmploymentDate) values (44, '5/4/2017');
insert into Teachers (ID, EmploymentDate) values (45, '11/4/2007');
insert into Teachers (ID, EmploymentDate) values (46, '27/4/2003');
insert into Teachers (ID, EmploymentDate) values (47, '23/6/2020');
insert into Teachers (ID, EmploymentDate) values (48, '28/3/1994');
insert into Teachers (ID, EmploymentDate) values (49, '29/4/2004');
insert into Teachers (ID, EmploymentDate) values (50, '4/8/1992');
insert into Teachers (ID, EmploymentDate) values (51, '4/2/2002');
insert into Teachers (ID, EmploymentDate) values (52, '5/1/2004');
insert into Teachers (ID, EmploymentDate) values (53, '17/1/1995');
insert into Teachers (ID, EmploymentDate) values (54, '9/10/2013');
insert into Teachers (ID, EmploymentDate) values (55, '8/12/1995');
insert into Teachers (ID, EmploymentDate) values (56, '19/7/2016');
insert into Teachers (ID, EmploymentDate) values (57, '22/6/2021');
insert into Teachers (ID, EmploymentDate) values (58, '15/2/2025');
insert into Teachers (ID, EmploymentDate) values (59, '17/2/2015');
insert into Teachers (ID, EmploymentDate) values (60, '19/5/2004');
insert into Teachers (ID, EmploymentDate) values (61, '8/1/2024');
insert into Teachers (ID, EmploymentDate) values (62, '10/6/2013');
insert into Teachers (ID, EmploymentDate) values (63, '21/8/2018');
insert into Teachers (ID, EmploymentDate) values (64, '1/10/2005');
insert into Teachers (ID, EmploymentDate) values (65, '14/11/1992');
insert into Teachers (ID, EmploymentDate) values (66, '26/8/2001');
insert into Teachers (ID, EmploymentDate) values (67, '3/7/2005');
insert into Teachers (ID, EmploymentDate) values (68, '31/12/2006');
insert into Teachers (ID, EmploymentDate) values (69, '6/8/2000');
insert into Teachers (ID, EmploymentDate) values (70, '2/4/2004');
insert into Teachers (ID, EmploymentDate) values (71, '11/6/1991');
insert into Teachers (ID, EmploymentDate) values (72, '2/5/2017');
insert into Teachers (ID, EmploymentDate) values (73, '21/7/1996');
insert into Teachers (ID, EmploymentDate) values (74, '14/3/2016');
insert into Teachers (ID, EmploymentDate) values (75, '27/9/2003');
insert into Teachers (ID, EmploymentDate) values (76, '25/8/2024');
insert into Teachers (ID, EmploymentDate) values (77, '30/8/1990');
insert into Teachers (ID, EmploymentDate) values (78, '19/7/2012');
insert into Teachers (ID, EmploymentDate) values (79, '26/7/2015');
insert into Teachers (ID, EmploymentDate) values (80, '24/11/2019');
insert into Teachers (ID, EmploymentDate) values (81, '1/12/1999');
insert into Teachers (ID, EmploymentDate) values (82, '28/7/1994');
insert into Teachers (ID, EmploymentDate) values (83, '12/5/2010');
insert into Teachers (ID, EmploymentDate) values (84, '10/8/2010');
insert into Teachers (ID, EmploymentDate) values (85, '2/1/2008');
insert into Teachers (ID, EmploymentDate) values (86, '23/2/2023');
insert into Teachers (ID, EmploymentDate) values (87, '25/2/2023');
insert into Teachers (ID, EmploymentDate) values (88, '18/2/2024');
insert into Teachers (ID, EmploymentDate) values (89, '13/12/2018');
insert into Teachers (ID, EmploymentDate) values (90, '8/11/1989');
insert into Teachers (ID, EmploymentDate) values (91, '1/3/2022');
insert into Teachers (ID, EmploymentDate) values (92, '4/3/2017');
insert into Teachers (ID, EmploymentDate) values (93, '22/9/1993');
insert into Teachers (ID, EmploymentDate) values (94, '13/5/1993');
insert into Teachers (ID, EmploymentDate) values (95, '28/8/2008');
insert into Teachers (ID, EmploymentDate) values (96, '1/8/2017');
insert into Teachers (ID, EmploymentDate) values (97, '9/2/2015');
insert into Teachers (ID, EmploymentDate) values (98, '4/2/2020');
insert into Teachers (ID, EmploymentDate) values (99, '6/10/2001');
insert into Teachers (ID, EmploymentDate) values (100, '23/3/2021');
